# Generated by Django 4.1.5 on 2023-01-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('autumn', 'autumn'), ('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=None, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.description'),
        ),
    ]
