# Generated by Django 4.1.5 on 2023-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_description_alter_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
