# Generated by Django 4.1.5 on 2023-01-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_description_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.description'),
        ),
    ]
