# Generated by Django 4.1.5 on 2023-01-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_time']},
        ),
    ]
